### ISSUE TITLE
Multi Store site magento 2.3.3 not generate the url correctly 

### ISSUE THREAD

**Issue by vandark25** [elgentos/regenerate-catalog-urls#41] opened 2020-09-29 15:31 UTC
Hello
![2020-09-29](https://user-images.githubusercontent.com/40995825/94575372-76f28800-0274-11eb-9baa-6f92b9b81a7c.png)

When we generate a url for example in the language portgues, instead of generating the url based on the name of the category in Portuguese, generates it with the default language ( english ) and does not change the url field within your language.

BAD URL: /cuchilleria/navajas/navajas -de-barbero.html

Requested URL /cutileria/navaljas/navalhas-do-barbero.html

**Comment by peterjaap** [comment] 2020-09-30 13:09
What's the command you are running?

**Comment by vandark25** [comment] 2020-09-30 13:29
php bin/magento regenerate:category:url --store=6 358 
or 
php bin/magento regenerate:category:path --store=6 358 

in both cases the url of scope 6 not change the checkbox "use default value" and dont put the name of category on the selected language

**Comment by peterjaap** [comment] 2020-09-30 13:39
Sorry my Portuguese is non-existent. Could you supply me with the values in the default store and in store code 6 for both the product and the category?

**Comment by vandark25** [comment] 2020-09-30 13:54
Values on Admin value and spanish value (defatult) Store id 0 and spanish its 1 (but use default values)
/cuchilleria/navajas/navajas -de-barbero.html Value for Store id 0
/cutileria/navaljas/navalhas-do-barbero.html Values for store id  6

![spanish](https://user-images.githubusercontent.com/40995825/94694260-f182dc80-0334-11eb-885d-ca9bc5d17456.png)
![image](https://user-images.githubusercontent.com/40995825/94694281-f6e02700-0334-11eb-8032-07e0a3a58991.png)

**Comment by peterjaap** [comment] 2020-09-30 14:14
I have the feeling this is similar to #27 and #28 which should have been fixed with #33. Are you sure you're running the latest version?

**Comment by vandark25** [comment] 2020-09-30 14:43
Yes 0.2.5
 "name": "elgentos/regenerate-catalog-urls",
            "version": "0.2.5",
            "source": {
                "type": "git",
                "url": "https://github.com/elgentos/regenerate-catalog-urls.git",
                "reference": "0274f47663309671134b87ced0683f3b75896d66"

**Comment by peterjaap** [comment] 2020-09-30 14:49
Well actually 0.2.6 is the latest version (since yesterday) but that shouldn't matter in this case. 

What if you delete the offending url rewrites before you regenerate them?

**Comment by vandark25** [comment] 2020-09-30 15:44
It's the same 

All the urls I'm trying to create don't exist yet

**Comment by vandark25** [comment] 2020-10-01 08:22
Any help for this ?

**Comment by peterjaap** [comment] 2020-10-01 08:49
Sorry I don't have a lot of time right now. Maybe you can try one of [this (deprecated) alternative](https://github.com/experius/Magento2-Module-Experius-ReindexCatalogUrlRewrites) to this extension and see if thesame thing happens there.

**Comment by peterjaap** [comment] 2020-10-01 08:50
Or this one; https://github.com/olegkoval/magento2-regenerate_url_rewrites

**Comment by peterjaap** [comment] 2020-10-01 08:52
Let me know if that fixes it for you so I know whether the problem is in the extension or in your particular installation.

**Comment by vandark25** [comment] 2020-10-01 20:04
Oleg's extension, we have used it several times, the problem is that now with the big shop, the generation of the categories takes a long time and the process ends up shutting down before it is finished

On the other hand, your extension ends after a few seconds, but it does not do it well

**Comment by vandark25** [comment] 2020-10-03 10:54
The others extensións don't works. Oleg create the Firts level but not the intermediate levels and stuck the database. The other code show a mysql error

**Comment by peterjaap** [comment] 2020-10-03 11:29
Since I can't reproduce the error on my end and the other two extensions also don't work, the most likely cause is in your installation, and not in the extension, and I won't be able to help you with that.

**Comment by vandark25** [comment] 2020-10-05 11:54
And could you check my installation?

**Comment by peterjaap** [comment] 2020-10-05 12:22
No sorry.

**Comment by paugnu** [comment] 2021-06-08 16:11
Hi,

After a lot of investigation, I've found that:
* This module uses deprecated functions (based on url_path)
* Because of this, given that url_path is not used anymore, the urls for store views are not correctly generated
* We need to check: vendor/magento/module-catalog-url-rewrite/Model/ProductUrlPathGenerator.php (line 79)
 
When they execute:
`$path = $product->getData('url_path');`

This might return the path for the default store view. I'll check if I can solve this somehow...

**Comment by peterjaap** [comment] 2021-06-08 20:23
@paugnu yes, see the Readme; https://github.com/elgentos/regenerate-catalog-urls#whats-the-difference-between-url_key-and-url_path

**Comment by peterjaap** [comment] 2021-06-29 15:02
Closing this issue since it seems to be related to `url_path` values still being present in a non-2.1 Magento install.

**Closed by peterjaap** 2021-06-29 15:02 UTC
